bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
branches:
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-lts
    branch: 1.113.14-sp
- bumpMinorPreMajor: true
  handleGHRelease: true
  releaseType: java-lts
  branch: 1.106.1