bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
extraFiles:
  - README.md
  - .readme-partials.yaml
branches:
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-lts
    branch: 1.113.14-sp
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-yoshi
    branch: 1.106.1-patch
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-yoshi
    branch: 1.111.3-patch
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-yoshi
    branch: java7
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-yoshi
    branch: 2.1.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 2.6.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 2.15.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    extraFiles:
      - README.md
    branch: 2.22.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    extraFiles:
      - README.md
    branch: 2.30.x
