rebaseMergeAllowed: false
squashMergeAllowed: true
mergeCommitAllowed: false
branchProtectionRules:
  - pattern: main
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (17)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
      - 'Kokoro - Test: Java GraalVM Native Image'
      - 'Kokoro - Test: Java 17 GraalVM Native Image'
      - javadoc
      - unmanaged_dependency_check
  - pattern: 1.113.14-sp
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (7)
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
  - pattern: java7
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (7)
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
  - pattern: 2.1.x
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
  - pattern: 2.6.x
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
      - OwlBot Post Processor
      - 'Kokoro - Test: Java GraalVM Native Image'
      - 'Kokoro - Test: Java 17 GraalVM Native Image'
  - pattern: 2.15.x
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
      - OwlBot Post Processor
      - 'Kokoro - Test: Java GraalVM Native Image'
      - 'Kokoro - Test: Java 17 GraalVM Native Image'
  - pattern: feat/breaking-preview
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
      - 'Kokoro - Test: Java GraalVM Native Image'
      - 'Kokoro - Test: Java 17 GraalVM Native Image'
  - pattern: 2.22.x
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (8)
      - dependencies (11)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
      - OwlBot Post Processor
      - 'Kokoro - Test: Java GraalVM Native Image'
      - 'Kokoro - Test: Java 17 GraalVM Native Image'
  - pattern: 2.30.x
    isAdminEnforced: true
    requiredApprovingReviewCount: 1
    requiresCodeOwnerReviews: true
    requiresStrictStatusChecks: false
    requiredStatusCheckContexts:
      - dependencies (17)
      - lint
      - clirr
      - units (8)
      - units (11)
      - 'Kokoro - Test: Integration'
      - cla/google
      - OwlBot Post Processor
      - 'Kokoro - Test: Java GraalVM Native Image'
      - 'Kokoro - Test: Java 17 GraalVM Native Image'
      - javadoc
permissionRules:
  - team: yoshi-admins
    permission: admin
  - team: yoshi-java-admins
    permission: admin
  - team: yoshi-java
    permission: push
