// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/storage/control/v2/storage_control.proto

package com.google.storage.control.v2;

public interface PendingRenameInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.storage.control.v2.PendingRenameInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Output only. The name of the rename operation.
   * </pre>
   *
   * <code>string operation = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The operation.
   */
  java.lang.String getOperation();
  /**
   * <pre>
   * Output only. The name of the rename operation.
   * </pre>
   *
   * <code>string operation = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   * @return The bytes for operation.
   */
  com.google.protobuf.ByteString
      getOperationBytes();
}
