/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/storage/v1/storage_resources.proto

package com.google.storage.v1;

public interface BucketOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.storage.v1.Bucket)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Access controls on the bucket.
   * </pre>
   *
   * <code>repeated .google.storage.v1.BucketAccessControl acl = 1;</code>
   */
  java.util.List<com.google.storage.v1.BucketAccessControl> getAclList();
  /**
   *
   *
   * <pre>
   * Access controls on the bucket.
   * </pre>
   *
   * <code>repeated .google.storage.v1.BucketAccessControl acl = 1;</code>
   */
  com.google.storage.v1.BucketAccessControl getAcl(int index);
  /**
   *
   *
   * <pre>
   * Access controls on the bucket.
   * </pre>
   *
   * <code>repeated .google.storage.v1.BucketAccessControl acl = 1;</code>
   */
  int getAclCount();
  /**
   *
   *
   * <pre>
   * Access controls on the bucket.
   * </pre>
   *
   * <code>repeated .google.storage.v1.BucketAccessControl acl = 1;</code>
   */
  java.util.List<? extends com.google.storage.v1.BucketAccessControlOrBuilder>
      getAclOrBuilderList();
  /**
   *
   *
   * <pre>
   * Access controls on the bucket.
   * </pre>
   *
   * <code>repeated .google.storage.v1.BucketAccessControl acl = 1;</code>
   */
  com.google.storage.v1.BucketAccessControlOrBuilder getAclOrBuilder(int index);

  /**
   *
   *
   * <pre>
   * Default access controls to apply to new objects when no ACL is provided.
   * </pre>
   *
   * <code>repeated .google.storage.v1.ObjectAccessControl default_object_acl = 2;</code>
   */
  java.util.List<com.google.storage.v1.ObjectAccessControl> getDefaultObjectAclList();
  /**
   *
   *
   * <pre>
   * Default access controls to apply to new objects when no ACL is provided.
   * </pre>
   *
   * <code>repeated .google.storage.v1.ObjectAccessControl default_object_acl = 2;</code>
   */
  com.google.storage.v1.ObjectAccessControl getDefaultObjectAcl(int index);
  /**
   *
   *
   * <pre>
   * Default access controls to apply to new objects when no ACL is provided.
   * </pre>
   *
   * <code>repeated .google.storage.v1.ObjectAccessControl default_object_acl = 2;</code>
   */
  int getDefaultObjectAclCount();
  /**
   *
   *
   * <pre>
   * Default access controls to apply to new objects when no ACL is provided.
   * </pre>
   *
   * <code>repeated .google.storage.v1.ObjectAccessControl default_object_acl = 2;</code>
   */
  java.util.List<? extends com.google.storage.v1.ObjectAccessControlOrBuilder>
      getDefaultObjectAclOrBuilderList();
  /**
   *
   *
   * <pre>
   * Default access controls to apply to new objects when no ACL is provided.
   * </pre>
   *
   * <code>repeated .google.storage.v1.ObjectAccessControl default_object_acl = 2;</code>
   */
  com.google.storage.v1.ObjectAccessControlOrBuilder getDefaultObjectAclOrBuilder(int index);

  /**
   *
   *
   * <pre>
   * The bucket's lifecycle configuration. See
   * [https://developers.google.com/storage/docs/lifecycle]Lifecycle Management]
   * for more information.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Lifecycle lifecycle = 3;</code>
   *
   * @return Whether the lifecycle field is set.
   */
  boolean hasLifecycle();
  /**
   *
   *
   * <pre>
   * The bucket's lifecycle configuration. See
   * [https://developers.google.com/storage/docs/lifecycle]Lifecycle Management]
   * for more information.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Lifecycle lifecycle = 3;</code>
   *
   * @return The lifecycle.
   */
  com.google.storage.v1.Bucket.Lifecycle getLifecycle();
  /**
   *
   *
   * <pre>
   * The bucket's lifecycle configuration. See
   * [https://developers.google.com/storage/docs/lifecycle]Lifecycle Management]
   * for more information.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Lifecycle lifecycle = 3;</code>
   */
  com.google.storage.v1.Bucket.LifecycleOrBuilder getLifecycleOrBuilder();

  /**
   *
   *
   * <pre>
   * The creation time of the bucket in
   * [https://tools.ietf.org/html/rfc3339][RFC 3339] format.
   * Attempting to set this field will result in an error.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time_created = 4;</code>
   *
   * @return Whether the timeCreated field is set.
   */
  boolean hasTimeCreated();
  /**
   *
   *
   * <pre>
   * The creation time of the bucket in
   * [https://tools.ietf.org/html/rfc3339][RFC 3339] format.
   * Attempting to set this field will result in an error.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time_created = 4;</code>
   *
   * @return The timeCreated.
   */
  com.google.protobuf.Timestamp getTimeCreated();
  /**
   *
   *
   * <pre>
   * The creation time of the bucket in
   * [https://tools.ietf.org/html/rfc3339][RFC 3339] format.
   * Attempting to set this field will result in an error.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp time_created = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimeCreatedOrBuilder();

  /**
   *
   *
   * <pre>
   * The ID of the bucket. For buckets, the `id` and `name` properties are the
   * same.
   * Attempting to update this field after the bucket is created will result in
   * an error.
   * </pre>
   *
   * <code>string id = 5;</code>
   *
   * @return The id.
   */
  java.lang.String getId();
  /**
   *
   *
   * <pre>
   * The ID of the bucket. For buckets, the `id` and `name` properties are the
   * same.
   * Attempting to update this field after the bucket is created will result in
   * an error.
   * </pre>
   *
   * <code>string id = 5;</code>
   *
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString getIdBytes();

  /**
   *
   *
   * <pre>
   * The name of the bucket.
   * Attempting to update this field after the bucket is created will result in
   * an error.
   * </pre>
   *
   * <code>string name = 6;</code>
   *
   * @return The name.
   */
  java.lang.String getName();
  /**
   *
   *
   * <pre>
   * The name of the bucket.
   * Attempting to update this field after the bucket is created will result in
   * an error.
   * </pre>
   *
   * <code>string name = 6;</code>
   *
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString getNameBytes();

  /**
   *
   *
   * <pre>
   * The project number of the project the bucket belongs to.
   * Attempting to set this field will result in an error.
   * </pre>
   *
   * <code>int64 project_number = 7;</code>
   *
   * @return The projectNumber.
   */
  long getProjectNumber();

  /**
   *
   *
   * <pre>
   * The metadata generation of this bucket.
   * Attempting to set this field will result in an error.
   * </pre>
   *
   * <code>int64 metageneration = 8;</code>
   *
   * @return The metageneration.
   */
  long getMetageneration();

  /**
   *
   *
   * <pre>
   * The bucket's [https://www.w3.org/TR/cors/][Cross-Origin Resource Sharing]
   * (CORS) configuration.
   * </pre>
   *
   * <code>repeated .google.storage.v1.Bucket.Cors cors = 9;</code>
   */
  java.util.List<com.google.storage.v1.Bucket.Cors> getCorsList();
  /**
   *
   *
   * <pre>
   * The bucket's [https://www.w3.org/TR/cors/][Cross-Origin Resource Sharing]
   * (CORS) configuration.
   * </pre>
   *
   * <code>repeated .google.storage.v1.Bucket.Cors cors = 9;</code>
   */
  com.google.storage.v1.Bucket.Cors getCors(int index);
  /**
   *
   *
   * <pre>
   * The bucket's [https://www.w3.org/TR/cors/][Cross-Origin Resource Sharing]
   * (CORS) configuration.
   * </pre>
   *
   * <code>repeated .google.storage.v1.Bucket.Cors cors = 9;</code>
   */
  int getCorsCount();
  /**
   *
   *
   * <pre>
   * The bucket's [https://www.w3.org/TR/cors/][Cross-Origin Resource Sharing]
   * (CORS) configuration.
   * </pre>
   *
   * <code>repeated .google.storage.v1.Bucket.Cors cors = 9;</code>
   */
  java.util.List<? extends com.google.storage.v1.Bucket.CorsOrBuilder> getCorsOrBuilderList();
  /**
   *
   *
   * <pre>
   * The bucket's [https://www.w3.org/TR/cors/][Cross-Origin Resource Sharing]
   * (CORS) configuration.
   * </pre>
   *
   * <code>repeated .google.storage.v1.Bucket.Cors cors = 9;</code>
   */
  com.google.storage.v1.Bucket.CorsOrBuilder getCorsOrBuilder(int index);

  /**
   *
   *
   * <pre>
   * The location of the bucket. Object data for objects in the bucket resides
   * in physical storage within this region.  Defaults to `US`. See the
   * [https://developers.google.com/storage/docs/concepts-techniques#specifyinglocations"][developer's
   * guide] for the authoritative list. Attempting to update this field after
   * the bucket is created will result in an error.
   * </pre>
   *
   * <code>string location = 10;</code>
   *
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   *
   *
   * <pre>
   * The location of the bucket. Object data for objects in the bucket resides
   * in physical storage within this region.  Defaults to `US`. See the
   * [https://developers.google.com/storage/docs/concepts-techniques#specifyinglocations"][developer's
   * guide] for the authoritative list. Attempting to update this field after
   * the bucket is created will result in an error.
   * </pre>
   *
   * <code>string location = 10;</code>
   *
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString getLocationBytes();

  /**
   *
   *
   * <pre>
   * The bucket's default storage class, used whenever no storageClass is
   * specified for a newly-created object. This defines how objects in the
   * bucket are stored and determines the SLA and the cost of storage.
   * If this value is not specified when the bucket is created, it will default
   * to `STANDARD`. For more information, see
   * https://developers.google.com/storage/docs/storage-classes.
   * </pre>
   *
   * <code>string storage_class = 11;</code>
   *
   * @return The storageClass.
   */
  java.lang.String getStorageClass();
  /**
   *
   *
   * <pre>
   * The bucket's default storage class, used whenever no storageClass is
   * specified for a newly-created object. This defines how objects in the
   * bucket are stored and determines the SLA and the cost of storage.
   * If this value is not specified when the bucket is created, it will default
   * to `STANDARD`. For more information, see
   * https://developers.google.com/storage/docs/storage-classes.
   * </pre>
   *
   * <code>string storage_class = 11;</code>
   *
   * @return The bytes for storageClass.
   */
  com.google.protobuf.ByteString getStorageClassBytes();

  /**
   *
   *
   * <pre>
   * HTTP 1.1 [https://tools.ietf.org/html/rfc7232#section-2.3"]Entity tag]
   * for the bucket.
   * Attempting to set this field will result in an error.
   * </pre>
   *
   * <code>string etag = 12;</code>
   *
   * @return The etag.
   */
  java.lang.String getEtag();
  /**
   *
   *
   * <pre>
   * HTTP 1.1 [https://tools.ietf.org/html/rfc7232#section-2.3"]Entity tag]
   * for the bucket.
   * Attempting to set this field will result in an error.
   * </pre>
   *
   * <code>string etag = 12;</code>
   *
   * @return The bytes for etag.
   */
  com.google.protobuf.ByteString getEtagBytes();

  /**
   *
   *
   * <pre>
   * The modification time of the bucket.
   * Attempting to set this field will result in an error.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated = 13;</code>
   *
   * @return Whether the updated field is set.
   */
  boolean hasUpdated();
  /**
   *
   *
   * <pre>
   * The modification time of the bucket.
   * Attempting to set this field will result in an error.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated = 13;</code>
   *
   * @return The updated.
   */
  com.google.protobuf.Timestamp getUpdated();
  /**
   *
   *
   * <pre>
   * The modification time of the bucket.
   * Attempting to set this field will result in an error.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp updated = 13;</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdatedOrBuilder();

  /**
   *
   *
   * <pre>
   * The default value for event-based hold on newly created objects in this
   * bucket.  Event-based hold is a way to retain objects indefinitely until an
   * event occurs, signified by the
   * hold's release. After being released, such objects will be subject to
   * bucket-level retention (if any).  One sample use case of this flag is for
   * banks to hold loan documents for at least 3 years after loan is paid in
   * full. Here, bucket-level retention is 3 years and the event is loan being
   * paid in full. In this example, these objects will be held intact for any
   * number of years until the event has occurred (event-based hold on the
   * object is released) and then 3 more years after that. That means retention
   * duration of the objects begins from the moment event-based hold
   * transitioned from true to false.  Objects under event-based hold cannot be
   * deleted, overwritten or archived until the hold is removed.
   * </pre>
   *
   * <code>bool default_event_based_hold = 14;</code>
   *
   * @return The defaultEventBasedHold.
   */
  boolean getDefaultEventBasedHold();

  /**
   *
   *
   * <pre>
   * User-provided labels, in key/value pairs.
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 15;</code>
   */
  int getLabelsCount();
  /**
   *
   *
   * <pre>
   * User-provided labels, in key/value pairs.
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 15;</code>
   */
  boolean containsLabels(java.lang.String key);
  /** Use {@link #getLabelsMap()} instead. */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String> getLabels();
  /**
   *
   *
   * <pre>
   * User-provided labels, in key/value pairs.
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 15;</code>
   */
  java.util.Map<java.lang.String, java.lang.String> getLabelsMap();
  /**
   *
   *
   * <pre>
   * User-provided labels, in key/value pairs.
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 15;</code>
   */
  java.lang.String getLabelsOrDefault(java.lang.String key, java.lang.String defaultValue);
  /**
   *
   *
   * <pre>
   * User-provided labels, in key/value pairs.
   * </pre>
   *
   * <code>map&lt;string, string&gt; labels = 15;</code>
   */
  java.lang.String getLabelsOrThrow(java.lang.String key);

  /**
   *
   *
   * <pre>
   * The bucket's website configuration, controlling how the service behaves
   * when accessing bucket contents as a web site. See the
   * [https://cloud.google.com/storage/docs/static-website][Static Website
   * Examples] for more information.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Website website = 16;</code>
   *
   * @return Whether the website field is set.
   */
  boolean hasWebsite();
  /**
   *
   *
   * <pre>
   * The bucket's website configuration, controlling how the service behaves
   * when accessing bucket contents as a web site. See the
   * [https://cloud.google.com/storage/docs/static-website][Static Website
   * Examples] for more information.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Website website = 16;</code>
   *
   * @return The website.
   */
  com.google.storage.v1.Bucket.Website getWebsite();
  /**
   *
   *
   * <pre>
   * The bucket's website configuration, controlling how the service behaves
   * when accessing bucket contents as a web site. See the
   * [https://cloud.google.com/storage/docs/static-website][Static Website
   * Examples] for more information.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Website website = 16;</code>
   */
  com.google.storage.v1.Bucket.WebsiteOrBuilder getWebsiteOrBuilder();

  /**
   *
   *
   * <pre>
   * The bucket's versioning configuration.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Versioning versioning = 17;</code>
   *
   * @return Whether the versioning field is set.
   */
  boolean hasVersioning();
  /**
   *
   *
   * <pre>
   * The bucket's versioning configuration.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Versioning versioning = 17;</code>
   *
   * @return The versioning.
   */
  com.google.storage.v1.Bucket.Versioning getVersioning();
  /**
   *
   *
   * <pre>
   * The bucket's versioning configuration.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Versioning versioning = 17;</code>
   */
  com.google.storage.v1.Bucket.VersioningOrBuilder getVersioningOrBuilder();

  /**
   *
   *
   * <pre>
   * The bucket's logging configuration, which defines the destination bucket
   * and optional name prefix for the current bucket's logs.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Logging logging = 18;</code>
   *
   * @return Whether the logging field is set.
   */
  boolean hasLogging();
  /**
   *
   *
   * <pre>
   * The bucket's logging configuration, which defines the destination bucket
   * and optional name prefix for the current bucket's logs.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Logging logging = 18;</code>
   *
   * @return The logging.
   */
  com.google.storage.v1.Bucket.Logging getLogging();
  /**
   *
   *
   * <pre>
   * The bucket's logging configuration, which defines the destination bucket
   * and optional name prefix for the current bucket's logs.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Logging logging = 18;</code>
   */
  com.google.storage.v1.Bucket.LoggingOrBuilder getLoggingOrBuilder();

  /**
   *
   *
   * <pre>
   * The owner of the bucket. This is always the project team's owner group.
   * </pre>
   *
   * <code>.google.storage.v1.Owner owner = 19;</code>
   *
   * @return Whether the owner field is set.
   */
  boolean hasOwner();
  /**
   *
   *
   * <pre>
   * The owner of the bucket. This is always the project team's owner group.
   * </pre>
   *
   * <code>.google.storage.v1.Owner owner = 19;</code>
   *
   * @return The owner.
   */
  com.google.storage.v1.Owner getOwner();
  /**
   *
   *
   * <pre>
   * The owner of the bucket. This is always the project team's owner group.
   * </pre>
   *
   * <code>.google.storage.v1.Owner owner = 19;</code>
   */
  com.google.storage.v1.OwnerOrBuilder getOwnerOrBuilder();

  /**
   *
   *
   * <pre>
   * Encryption configuration for a bucket.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Encryption encryption = 20;</code>
   *
   * @return Whether the encryption field is set.
   */
  boolean hasEncryption();
  /**
   *
   *
   * <pre>
   * Encryption configuration for a bucket.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Encryption encryption = 20;</code>
   *
   * @return The encryption.
   */
  com.google.storage.v1.Bucket.Encryption getEncryption();
  /**
   *
   *
   * <pre>
   * Encryption configuration for a bucket.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Encryption encryption = 20;</code>
   */
  com.google.storage.v1.Bucket.EncryptionOrBuilder getEncryptionOrBuilder();

  /**
   *
   *
   * <pre>
   * The bucket's billing configuration.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Billing billing = 21;</code>
   *
   * @return Whether the billing field is set.
   */
  boolean hasBilling();
  /**
   *
   *
   * <pre>
   * The bucket's billing configuration.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Billing billing = 21;</code>
   *
   * @return The billing.
   */
  com.google.storage.v1.Bucket.Billing getBilling();
  /**
   *
   *
   * <pre>
   * The bucket's billing configuration.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.Billing billing = 21;</code>
   */
  com.google.storage.v1.Bucket.BillingOrBuilder getBillingOrBuilder();

  /**
   *
   *
   * <pre>
   * The bucket's retention policy. The retention policy enforces a minimum
   * retention time for all objects contained in the bucket, based on their
   * creation time. Any attempt to overwrite or delete objects younger than the
   * retention period will result in a PERMISSION_DENIED error.  An unlocked
   * retention policy can be modified or removed from the bucket via a
   * storage.buckets.update operation. A locked retention policy cannot be
   * removed or shortened in duration for the lifetime of the bucket.
   * Attempting to remove or decrease period of a locked retention policy will
   * result in a PERMISSION_DENIED error.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.RetentionPolicy retention_policy = 22;</code>
   *
   * @return Whether the retentionPolicy field is set.
   */
  boolean hasRetentionPolicy();
  /**
   *
   *
   * <pre>
   * The bucket's retention policy. The retention policy enforces a minimum
   * retention time for all objects contained in the bucket, based on their
   * creation time. Any attempt to overwrite or delete objects younger than the
   * retention period will result in a PERMISSION_DENIED error.  An unlocked
   * retention policy can be modified or removed from the bucket via a
   * storage.buckets.update operation. A locked retention policy cannot be
   * removed or shortened in duration for the lifetime of the bucket.
   * Attempting to remove or decrease period of a locked retention policy will
   * result in a PERMISSION_DENIED error.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.RetentionPolicy retention_policy = 22;</code>
   *
   * @return The retentionPolicy.
   */
  com.google.storage.v1.Bucket.RetentionPolicy getRetentionPolicy();
  /**
   *
   *
   * <pre>
   * The bucket's retention policy. The retention policy enforces a minimum
   * retention time for all objects contained in the bucket, based on their
   * creation time. Any attempt to overwrite or delete objects younger than the
   * retention period will result in a PERMISSION_DENIED error.  An unlocked
   * retention policy can be modified or removed from the bucket via a
   * storage.buckets.update operation. A locked retention policy cannot be
   * removed or shortened in duration for the lifetime of the bucket.
   * Attempting to remove or decrease period of a locked retention policy will
   * result in a PERMISSION_DENIED error.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.RetentionPolicy retention_policy = 22;</code>
   */
  com.google.storage.v1.Bucket.RetentionPolicyOrBuilder getRetentionPolicyOrBuilder();

  /**
   *
   *
   * <pre>
   * The location type of the bucket (region, dual-region, multi-region, etc).
   * </pre>
   *
   * <code>string location_type = 23;</code>
   *
   * @return The locationType.
   */
  java.lang.String getLocationType();
  /**
   *
   *
   * <pre>
   * The location type of the bucket (region, dual-region, multi-region, etc).
   * </pre>
   *
   * <code>string location_type = 23;</code>
   *
   * @return The bytes for locationType.
   */
  com.google.protobuf.ByteString getLocationTypeBytes();

  /**
   *
   *
   * <pre>
   * The bucket's IAM configuration.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.IamConfiguration iam_configuration = 24;</code>
   *
   * @return Whether the iamConfiguration field is set.
   */
  boolean hasIamConfiguration();
  /**
   *
   *
   * <pre>
   * The bucket's IAM configuration.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.IamConfiguration iam_configuration = 24;</code>
   *
   * @return The iamConfiguration.
   */
  com.google.storage.v1.Bucket.IamConfiguration getIamConfiguration();
  /**
   *
   *
   * <pre>
   * The bucket's IAM configuration.
   * </pre>
   *
   * <code>.google.storage.v1.Bucket.IamConfiguration iam_configuration = 24;</code>
   */
  com.google.storage.v1.Bucket.IamConfigurationOrBuilder getIamConfigurationOrBuilder();

  /**
   *
   *
   * <pre>
   * The zone or zones from which the bucket is intended to use zonal quota.
   * Requests for data from outside the specified affinities are still allowed
   * but won’t be able to use zonal quota. The values are case-insensitive.
   * Attempting to update this field after bucket is created will result in an
   * error.
   * </pre>
   *
   * <code>repeated string zone_affinity = 25;</code>
   *
   * @return A list containing the zoneAffinity.
   */
  java.util.List<java.lang.String> getZoneAffinityList();
  /**
   *
   *
   * <pre>
   * The zone or zones from which the bucket is intended to use zonal quota.
   * Requests for data from outside the specified affinities are still allowed
   * but won’t be able to use zonal quota. The values are case-insensitive.
   * Attempting to update this field after bucket is created will result in an
   * error.
   * </pre>
   *
   * <code>repeated string zone_affinity = 25;</code>
   *
   * @return The count of zoneAffinity.
   */
  int getZoneAffinityCount();
  /**
   *
   *
   * <pre>
   * The zone or zones from which the bucket is intended to use zonal quota.
   * Requests for data from outside the specified affinities are still allowed
   * but won’t be able to use zonal quota. The values are case-insensitive.
   * Attempting to update this field after bucket is created will result in an
   * error.
   * </pre>
   *
   * <code>repeated string zone_affinity = 25;</code>
   *
   * @param index The index of the element to return.
   * @return The zoneAffinity at the given index.
   */
  java.lang.String getZoneAffinity(int index);
  /**
   *
   *
   * <pre>
   * The zone or zones from which the bucket is intended to use zonal quota.
   * Requests for data from outside the specified affinities are still allowed
   * but won’t be able to use zonal quota. The values are case-insensitive.
   * Attempting to update this field after bucket is created will result in an
   * error.
   * </pre>
   *
   * <code>repeated string zone_affinity = 25;</code>
   *
   * @param index The index of the value to return.
   * @return The bytes of the zoneAffinity at the given index.
   */
  com.google.protobuf.ByteString getZoneAffinityBytes(int index);
}
