/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/storage/v1/storage_resources.proto

package com.google.storage.v1;

public final class CloudStorageResourcesProto {
  private CloudStorageResourcesProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Bucket_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Bucket_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Bucket_Billing_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Bucket_Billing_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Bucket_Cors_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Bucket_Cors_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Bucket_Encryption_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Bucket_Encryption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Bucket_IamConfiguration_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Bucket_IamConfiguration_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Bucket_IamConfiguration_UniformBucketLevelAccess_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Bucket_IamConfiguration_UniformBucketLevelAccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Bucket_Lifecycle_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Bucket_Lifecycle_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Bucket_Lifecycle_Rule_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Bucket_Lifecycle_Rule_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Bucket_Lifecycle_Rule_Action_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Bucket_Lifecycle_Rule_Action_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Bucket_Lifecycle_Rule_Condition_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Bucket_Lifecycle_Rule_Condition_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Bucket_Logging_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Bucket_Logging_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Bucket_RetentionPolicy_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Bucket_RetentionPolicy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Bucket_Versioning_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Bucket_Versioning_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Bucket_Website_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Bucket_Website_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Bucket_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Bucket_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_BucketAccessControl_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_BucketAccessControl_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_ListBucketAccessControlsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_ListBucketAccessControlsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_ListBucketsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_ListBucketsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Channel_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Channel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Channel_ParamsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Channel_ParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_ListChannelsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_ListChannelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_ListChannelsResponse_Items_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_ListChannelsResponse_Items_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_ChecksummedData_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_ChecksummedData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_ObjectChecksums_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_ObjectChecksums_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_CommonEnums_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_CommonEnums_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_ContentRange_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_ContentRange_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_HmacKeyMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_HmacKeyMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Notification_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Notification_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Notification_CustomAttributesEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Notification_CustomAttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_ListNotificationsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_ListNotificationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Object_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Object_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Object_CustomerEncryption_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Object_CustomerEncryption_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Object_MetadataEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Object_MetadataEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_ObjectAccessControl_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_ObjectAccessControl_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_ListObjectAccessControlsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_ListObjectAccessControlsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_ListObjectsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_ListObjectsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_ProjectTeam_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_ProjectTeam_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_ServiceAccount_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_ServiceAccount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_storage_v1_Owner_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_storage_v1_Owner_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n)google/storage/v1/storage_resources.pr"
          + "oto\022\021google.storage.v1\032\037google/protobuf/"
          + "timestamp.proto\032\036google/protobuf/wrapper"
          + "s.proto\"\250\021\n\006Bucket\0223\n\003acl\030\001 \003(\0132&.google"
          + ".storage.v1.BucketAccessControl\022B\n\022defau"
          + "lt_object_acl\030\002 \003(\0132&.google.storage.v1."
          + "ObjectAccessControl\0226\n\tlifecycle\030\003 \001(\0132#"
          + ".google.storage.v1.Bucket.Lifecycle\0220\n\014t"
          + "ime_created\030\004 \001(\0132\032.google.protobuf.Time"
          + "stamp\022\n\n\002id\030\005 \001(\t\022\014\n\004name\030\006 \001(\t\022\026\n\016proje"
          + "ct_number\030\007 \001(\003\022\026\n\016metageneration\030\010 \001(\003\022"
          + ",\n\004cors\030\t \003(\0132\036.google.storage.v1.Bucket"
          + ".Cors\022\020\n\010location\030\n \001(\t\022\025\n\rstorage_class"
          + "\030\013 \001(\t\022\014\n\004etag\030\014 \001(\t\022+\n\007updated\030\r \001(\0132\032."
          + "google.protobuf.Timestamp\022 \n\030default_eve"
          + "nt_based_hold\030\016 \001(\010\0225\n\006labels\030\017 \003(\0132%.go"
          + "ogle.storage.v1.Bucket.LabelsEntry\0222\n\007we"
          + "bsite\030\020 \001(\0132!.google.storage.v1.Bucket.W"
          + "ebsite\0228\n\nversioning\030\021 \001(\0132$.google.stor"
          + "age.v1.Bucket.Versioning\0222\n\007logging\030\022 \001("
          + "\0132!.google.storage.v1.Bucket.Logging\022\'\n\005"
          + "owner\030\023 \001(\0132\030.google.storage.v1.Owner\0228\n"
          + "\nencryption\030\024 \001(\0132$.google.storage.v1.Bu"
          + "cket.Encryption\0222\n\007billing\030\025 \001(\0132!.googl"
          + "e.storage.v1.Bucket.Billing\022C\n\020retention"
          + "_policy\030\026 \001(\0132).google.storage.v1.Bucket"
          + ".RetentionPolicy\022\025\n\rlocation_type\030\027 \001(\t\022"
          + "E\n\021iam_configuration\030\030 \001(\0132*.google.stor"
          + "age.v1.Bucket.IamConfiguration\022\025\n\rzone_a"
          + "ffinity\030\031 \003(\t\032!\n\007Billing\022\026\n\016requester_pa"
          + "ys\030\001 \001(\010\032X\n\004Cors\022\016\n\006origin\030\001 \003(\t\022\016\n\006meth"
          + "od\030\002 \003(\t\022\027\n\017response_header\030\003 \003(\t\022\027\n\017max"
          + "_age_seconds\030\004 \001(\005\032*\n\nEncryption\022\034\n\024defa"
          + "ult_kms_key_name\030\001 \001(\t\032\332\001\n\020IamConfigurat"
          + "ion\022h\n\033uniform_bucket_level_access\030\001 \001(\013"
          + "2C.google.storage.v1.Bucket.IamConfigura"
          + "tion.UniformBucketLevelAccess\032\\\n\030Uniform"
          + "BucketLevelAccess\022\017\n\007enabled\030\001 \001(\010\022/\n\013lo"
          + "cked_time\030\002 \001(\0132\032.google.protobuf.Timest"
          + "amp\032\323\003\n\tLifecycle\0226\n\004rule\030\001 \003(\0132(.google"
          + ".storage.v1.Bucket.Lifecycle.Rule\032\215\003\n\004Ru"
          + "le\022?\n\006action\030\001 \001(\0132/.google.storage.v1.B"
          + "ucket.Lifecycle.Rule.Action\022E\n\tcondition"
          + "\030\002 \001(\01322.google.storage.v1.Bucket.Lifecy"
          + "cle.Rule.Condition\032-\n\006Action\022\014\n\004type\030\001 \001"
          + "(\t\022\025\n\rstorage_class\030\002 \001(\t\032\315\001\n\tCondition\022"
          + "\013\n\003age\030\001 \001(\005\0222\n\016created_before\030\002 \001(\0132\032.g"
          + "oogle.protobuf.Timestamp\022+\n\007is_live\030\003 \001("
          + "\0132\032.google.protobuf.BoolValue\022\032\n\022num_new"
          + "er_versions\030\004 \001(\005\022\035\n\025matches_storage_cla"
          + "ss\030\005 \003(\t\022\027\n\017matches_pattern\030\006 \001(\t\0328\n\007Log"
          + "ging\022\022\n\nlog_bucket\030\001 \001(\t\022\031\n\021log_object_p"
          + "refix\030\002 \001(\t\032r\n\017RetentionPolicy\0222\n\016effect"
          + "ive_time\030\001 \001(\0132\032.google.protobuf.Timesta"
          + "mp\022\021\n\tis_locked\030\002 \001(\010\022\030\n\020retention_perio"
          + "d\030\003 \001(\003\032\035\n\nVersioning\022\017\n\007enabled\030\001 \001(\010\032;"
          + "\n\007Website\022\030\n\020main_page_suffix\030\001 \001(\t\022\026\n\016n"
          + "ot_found_page\030\002 \001(\t\032-\n\013LabelsEntry\022\013\n\003ke"
          + "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\305\001\n\023BucketAcc"
          + "essControl\022\014\n\004role\030\001 \001(\t\022\014\n\004etag\030\002 \001(\t\022\n"
          + "\n\002id\030\003 \001(\t\022\016\n\006bucket\030\004 \001(\t\022\016\n\006entity\030\006 \001"
          + "(\t\022\021\n\tentity_id\030\007 \001(\t\022\r\n\005email\030\010 \001(\t\022\016\n\006"
          + "domain\030\t \001(\t\0224\n\014project_team\030\n \001(\0132\036.goo"
          + "gle.storage.v1.ProjectTeam\"Y\n ListBucket"
          + "AccessControlsResponse\0225\n\005items\030\001 \003(\0132&."
          + "google.storage.v1.BucketAccessControl\"X\n"
          + "\023ListBucketsResponse\022(\n\005items\030\001 \003(\0132\031.go"
          + "ogle.storage.v1.Bucket\022\027\n\017next_page_toke"
          + "n\030\002 \001(\t\"\226\002\n\007Channel\022\n\n\002id\030\001 \001(\t\022\023\n\013resou"
          + "rce_id\030\002 \001(\t\022\024\n\014resource_uri\030\003 \001(\t\022\r\n\005to"
          + "ken\030\004 \001(\t\022.\n\nexpiration\030\005 \001(\0132\032.google.p"
          + "rotobuf.Timestamp\022\014\n\004type\030\006 \001(\t\022\017\n\007addre"
          + "ss\030\007 \001(\t\0226\n\006params\030\010 \003(\0132&.google.storag"
          + "e.v1.Channel.ParamsEntry\022\017\n\007payload\030\t \001("
          + "\010\032-\n\013ParamsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002"
          + " \001(\t:\0028\001\"\346\001\n\024ListChannelsResponse\022<\n\005ite"
          + "ms\030\001 \003(\0132-.google.storage.v1.ListChannel"
          + "sResponse.Items\032\217\001\n\005Items\022\022\n\nchannel_id\030"
          + "\001 \001(\t\022\023\n\013resource_id\030\002 \001(\t\022\020\n\010push_url\030\003"
          + " \001(\t\022\030\n\020subscriber_email\030\004 \001(\t\0221\n\rcreati"
          + "on_time\030\005 \001(\0132\032.google.protobuf.Timestam"
          + "p\"P\n\017ChecksummedData\022\017\n\007content\030\001 \001(\014\022,\n"
          + "\006crc32c\030\002 \001(\0132\034.google.protobuf.UInt32Va"
          + "lue\"Q\n\017ObjectChecksums\022,\n\006crc32c\030\001 \001(\0132\034"
          + ".google.protobuf.UInt32Value\022\020\n\010md5_hash"
          + "\030\002 \001(\t\"\247\004\n\013CommonEnums\">\n\nProjection\022\032\n\026"
          + "PROJECTION_UNSPECIFIED\020\000\022\n\n\006NO_ACL\020\001\022\010\n\004"
          + "FULL\020\002\"\325\001\n\023PredefinedBucketAcl\022%\n!PREDEF"
          + "INED_BUCKET_ACL_UNSPECIFIED\020\000\022!\n\035BUCKET_"
          + "ACL_AUTHENTICATED_READ\020\001\022\026\n\022BUCKET_ACL_P"
          + "RIVATE\020\002\022\036\n\032BUCKET_ACL_PROJECT_PRIVATE\020\003"
          + "\022\032\n\026BUCKET_ACL_PUBLIC_READ\020\004\022 \n\034BUCKET_A"
          + "CL_PUBLIC_READ_WRITE\020\005\"\377\001\n\023PredefinedObj"
          + "ectAcl\022%\n!PREDEFINED_OBJECT_ACL_UNSPECIF"
          + "IED\020\000\022!\n\035OBJECT_ACL_AUTHENTICATED_READ\020\001"
          + "\022(\n$OBJECT_ACL_BUCKET_OWNER_FULL_CONTROL"
          + "\020\002\022 \n\034OBJECT_ACL_BUCKET_OWNER_READ\020\003\022\026\n\022"
          + "OBJECT_ACL_PRIVATE\020\004\022\036\n\032OBJECT_ACL_PROJE"
          + "CT_PRIVATE\020\005\022\032\n\026OBJECT_ACL_PUBLIC_READ\020\006"
          + "\"C\n\014ContentRange\022\r\n\005start\030\001 \001(\003\022\013\n\003end\030\002"
          + " \001(\003\022\027\n\017complete_length\030\003 \001(\003\"\337\001\n\017HmacKe"
          + "yMetadata\022\n\n\002id\030\001 \001(\t\022\021\n\taccess_id\030\002 \001(\t"
          + "\022\022\n\nproject_id\030\003 \001(\t\022\035\n\025service_account_"
          + "email\030\004 \001(\t\022\r\n\005state\030\005 \001(\t\0220\n\014time_creat"
          + "ed\030\006 \001(\0132\032.google.protobuf.Timestamp\022+\n\007"
          + "updated\030\007 \001(\0132\032.google.protobuf.Timestam"
          + "p\022\014\n\004etag\030\010 \001(\t\"\213\002\n\014Notification\022\r\n\005topi"
          + "c\030\001 \001(\t\022\023\n\013event_types\030\002 \003(\t\022P\n\021custom_a"
          + "ttributes\030\003 \003(\01325.google.storage.v1.Noti"
          + "fication.CustomAttributesEntry\022\014\n\004etag\030\004"
          + " \001(\t\022\032\n\022object_name_prefix\030\005 \001(\t\022\026\n\016payl"
          + "oad_format\030\006 \001(\t\022\n\n\002id\030\007 \001(\t\0327\n\025CustomAt"
          + "tributesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001("
          + "\t:\0028\001\"K\n\031ListNotificationsResponse\022.\n\005it"
          + "ems\030\001 \003(\0132\037.google.storage.v1.Notificati"
          + "on\"\271\010\n\006Object\022\030\n\020content_encoding\030\001 \001(\t\022"
          + "\033\n\023content_disposition\030\002 \001(\t\022\025\n\rcache_co"
          + "ntrol\030\003 \001(\t\0223\n\003acl\030\004 \003(\0132&.google.storag"
          + "e.v1.ObjectAccessControl\022\030\n\020content_lang"
          + "uage\030\005 \001(\t\022\026\n\016metageneration\030\006 \001(\003\0220\n\014ti"
          + "me_deleted\030\007 \001(\0132\032.google.protobuf.Times"
          + "tamp\022\024\n\014content_type\030\010 \001(\t\022\014\n\004size\030\t \001(\003"
          + "\0220\n\014time_created\030\n \001(\0132\032.google.protobuf"
          + ".Timestamp\022,\n\006crc32c\030\013 \001(\0132\034.google.prot"
          + "obuf.UInt32Value\022\027\n\017component_count\030\014 \001("
          + "\005\022\020\n\010md5_hash\030\r \001(\t\022\014\n\004etag\030\016 \001(\t\022+\n\007upd"
          + "ated\030\017 \001(\0132\032.google.protobuf.Timestamp\022\025"
          + "\n\rstorage_class\030\020 \001(\t\022\024\n\014kms_key_name\030\021 "
          + "\001(\t\022>\n\032time_storage_class_updated\030\022 \001(\0132"
          + "\032.google.protobuf.Timestamp\022\026\n\016temporary"
          + "_hold\030\023 \001(\010\022=\n\031retention_expiration_time"
          + "\030\024 \001(\0132\032.google.protobuf.Timestamp\0229\n\010me"
          + "tadata\030\025 \003(\0132\'.google.storage.v1.Object."
          + "MetadataEntry\0224\n\020event_based_hold\030\035 \001(\0132"
          + "\032.google.protobuf.BoolValue\022\014\n\004name\030\027 \001("
          + "\t\022\n\n\002id\030\030 \001(\t\022\016\n\006bucket\030\031 \001(\t\022\022\n\ngenerat"
          + "ion\030\032 \001(\003\022\'\n\005owner\030\033 \001(\0132\030.google.storag"
          + "e.v1.Owner\022I\n\023customer_encryption\030\034 \001(\0132"
          + ",.google.storage.v1.Object.CustomerEncry"
          + "ption\032F\n\022CustomerEncryption\022\034\n\024encryptio"
          + "n_algorithm\030\001 \001(\t\022\022\n\nkey_sha256\030\002 \001(\t\032/\n"
          + "\rMetadataEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001"
          + "(\t:\0028\001\"\351\001\n\023ObjectAccessControl\022\014\n\004role\030\001"
          + " \001(\t\022\014\n\004etag\030\002 \001(\t\022\n\n\002id\030\003 \001(\t\022\016\n\006bucket"
          + "\030\004 \001(\t\022\016\n\006object\030\005 \001(\t\022\022\n\ngeneration\030\006 \001"
          + "(\003\022\016\n\006entity\030\007 \001(\t\022\021\n\tentity_id\030\010 \001(\t\022\r\n"
          + "\005email\030\t \001(\t\022\016\n\006domain\030\n \001(\t\0224\n\014project_"
          + "team\030\013 \001(\0132\036.google.storage.v1.ProjectTe"
          + "am\"Y\n ListObjectAccessControlsResponse\0225"
          + "\n\005items\030\001 \003(\0132&.google.storage.v1.Object"
          + "AccessControl\"j\n\023ListObjectsResponse\022\020\n\010"
          + "prefixes\030\001 \003(\t\022(\n\005items\030\002 \003(\0132\031.google.s"
          + "torage.v1.Object\022\027\n\017next_page_token\030\003 \001("
          + "\t\"3\n\013ProjectTeam\022\026\n\016project_number\030\001 \001(\t"
          + "\022\014\n\004team\030\002 \001(\t\"\'\n\016ServiceAccount\022\025\n\remai"
          + "l_address\030\001 \001(\t\"*\n\005Owner\022\016\n\006entity\030\001 \001(\t"
          + "\022\021\n\tentity_id\030\002 \001(\tBo\n\025com.google.storag"
          + "e.v1B\032CloudStorageResourcesProtoP\001Z8goog"
          + "le.golang.org/genproto/googleapis/storag"
          + "e/v1;storageb\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.protobuf.WrappersProto.getDescriptor(),
            });
    internal_static_google_storage_v1_Bucket_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_google_storage_v1_Bucket_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Bucket_descriptor,
            new java.lang.String[] {
              "Acl",
              "DefaultObjectAcl",
              "Lifecycle",
              "TimeCreated",
              "Id",
              "Name",
              "ProjectNumber",
              "Metageneration",
              "Cors",
              "Location",
              "StorageClass",
              "Etag",
              "Updated",
              "DefaultEventBasedHold",
              "Labels",
              "Website",
              "Versioning",
              "Logging",
              "Owner",
              "Encryption",
              "Billing",
              "RetentionPolicy",
              "LocationType",
              "IamConfiguration",
              "ZoneAffinity",
            });
    internal_static_google_storage_v1_Bucket_Billing_descriptor =
        internal_static_google_storage_v1_Bucket_descriptor.getNestedTypes().get(0);
    internal_static_google_storage_v1_Bucket_Billing_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Bucket_Billing_descriptor,
            new java.lang.String[] {
              "RequesterPays",
            });
    internal_static_google_storage_v1_Bucket_Cors_descriptor =
        internal_static_google_storage_v1_Bucket_descriptor.getNestedTypes().get(1);
    internal_static_google_storage_v1_Bucket_Cors_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Bucket_Cors_descriptor,
            new java.lang.String[] {
              "Origin", "Method", "ResponseHeader", "MaxAgeSeconds",
            });
    internal_static_google_storage_v1_Bucket_Encryption_descriptor =
        internal_static_google_storage_v1_Bucket_descriptor.getNestedTypes().get(2);
    internal_static_google_storage_v1_Bucket_Encryption_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Bucket_Encryption_descriptor,
            new java.lang.String[] {
              "DefaultKmsKeyName",
            });
    internal_static_google_storage_v1_Bucket_IamConfiguration_descriptor =
        internal_static_google_storage_v1_Bucket_descriptor.getNestedTypes().get(3);
    internal_static_google_storage_v1_Bucket_IamConfiguration_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Bucket_IamConfiguration_descriptor,
            new java.lang.String[] {
              "UniformBucketLevelAccess",
            });
    internal_static_google_storage_v1_Bucket_IamConfiguration_UniformBucketLevelAccess_descriptor =
        internal_static_google_storage_v1_Bucket_IamConfiguration_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_storage_v1_Bucket_IamConfiguration_UniformBucketLevelAccess_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Bucket_IamConfiguration_UniformBucketLevelAccess_descriptor,
            new java.lang.String[] {
              "Enabled", "LockedTime",
            });
    internal_static_google_storage_v1_Bucket_Lifecycle_descriptor =
        internal_static_google_storage_v1_Bucket_descriptor.getNestedTypes().get(4);
    internal_static_google_storage_v1_Bucket_Lifecycle_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Bucket_Lifecycle_descriptor,
            new java.lang.String[] {
              "Rule",
            });
    internal_static_google_storage_v1_Bucket_Lifecycle_Rule_descriptor =
        internal_static_google_storage_v1_Bucket_Lifecycle_descriptor.getNestedTypes().get(0);
    internal_static_google_storage_v1_Bucket_Lifecycle_Rule_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Bucket_Lifecycle_Rule_descriptor,
            new java.lang.String[] {
              "Action", "Condition",
            });
    internal_static_google_storage_v1_Bucket_Lifecycle_Rule_Action_descriptor =
        internal_static_google_storage_v1_Bucket_Lifecycle_Rule_descriptor.getNestedTypes().get(0);
    internal_static_google_storage_v1_Bucket_Lifecycle_Rule_Action_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Bucket_Lifecycle_Rule_Action_descriptor,
            new java.lang.String[] {
              "Type", "StorageClass",
            });
    internal_static_google_storage_v1_Bucket_Lifecycle_Rule_Condition_descriptor =
        internal_static_google_storage_v1_Bucket_Lifecycle_Rule_descriptor.getNestedTypes().get(1);
    internal_static_google_storage_v1_Bucket_Lifecycle_Rule_Condition_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Bucket_Lifecycle_Rule_Condition_descriptor,
            new java.lang.String[] {
              "Age",
              "CreatedBefore",
              "IsLive",
              "NumNewerVersions",
              "MatchesStorageClass",
              "MatchesPattern",
            });
    internal_static_google_storage_v1_Bucket_Logging_descriptor =
        internal_static_google_storage_v1_Bucket_descriptor.getNestedTypes().get(5);
    internal_static_google_storage_v1_Bucket_Logging_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Bucket_Logging_descriptor,
            new java.lang.String[] {
              "LogBucket", "LogObjectPrefix",
            });
    internal_static_google_storage_v1_Bucket_RetentionPolicy_descriptor =
        internal_static_google_storage_v1_Bucket_descriptor.getNestedTypes().get(6);
    internal_static_google_storage_v1_Bucket_RetentionPolicy_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Bucket_RetentionPolicy_descriptor,
            new java.lang.String[] {
              "EffectiveTime", "IsLocked", "RetentionPeriod",
            });
    internal_static_google_storage_v1_Bucket_Versioning_descriptor =
        internal_static_google_storage_v1_Bucket_descriptor.getNestedTypes().get(7);
    internal_static_google_storage_v1_Bucket_Versioning_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Bucket_Versioning_descriptor,
            new java.lang.String[] {
              "Enabled",
            });
    internal_static_google_storage_v1_Bucket_Website_descriptor =
        internal_static_google_storage_v1_Bucket_descriptor.getNestedTypes().get(8);
    internal_static_google_storage_v1_Bucket_Website_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Bucket_Website_descriptor,
            new java.lang.String[] {
              "MainPageSuffix", "NotFoundPage",
            });
    internal_static_google_storage_v1_Bucket_LabelsEntry_descriptor =
        internal_static_google_storage_v1_Bucket_descriptor.getNestedTypes().get(9);
    internal_static_google_storage_v1_Bucket_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Bucket_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_storage_v1_BucketAccessControl_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_storage_v1_BucketAccessControl_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_BucketAccessControl_descriptor,
            new java.lang.String[] {
              "Role",
              "Etag",
              "Id",
              "Bucket",
              "Entity",
              "EntityId",
              "Email",
              "Domain",
              "ProjectTeam",
            });
    internal_static_google_storage_v1_ListBucketAccessControlsResponse_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_storage_v1_ListBucketAccessControlsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_ListBucketAccessControlsResponse_descriptor,
            new java.lang.String[] {
              "Items",
            });
    internal_static_google_storage_v1_ListBucketsResponse_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_storage_v1_ListBucketsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_ListBucketsResponse_descriptor,
            new java.lang.String[] {
              "Items", "NextPageToken",
            });
    internal_static_google_storage_v1_Channel_descriptor = getDescriptor().getMessageTypes().get(4);
    internal_static_google_storage_v1_Channel_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Channel_descriptor,
            new java.lang.String[] {
              "Id",
              "ResourceId",
              "ResourceUri",
              "Token",
              "Expiration",
              "Type",
              "Address",
              "Params",
              "Payload",
            });
    internal_static_google_storage_v1_Channel_ParamsEntry_descriptor =
        internal_static_google_storage_v1_Channel_descriptor.getNestedTypes().get(0);
    internal_static_google_storage_v1_Channel_ParamsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Channel_ParamsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_storage_v1_ListChannelsResponse_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_storage_v1_ListChannelsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_ListChannelsResponse_descriptor,
            new java.lang.String[] {
              "Items",
            });
    internal_static_google_storage_v1_ListChannelsResponse_Items_descriptor =
        internal_static_google_storage_v1_ListChannelsResponse_descriptor.getNestedTypes().get(0);
    internal_static_google_storage_v1_ListChannelsResponse_Items_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_ListChannelsResponse_Items_descriptor,
            new java.lang.String[] {
              "ChannelId", "ResourceId", "PushUrl", "SubscriberEmail", "CreationTime",
            });
    internal_static_google_storage_v1_ChecksummedData_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_storage_v1_ChecksummedData_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_ChecksummedData_descriptor,
            new java.lang.String[] {
              "Content", "Crc32C",
            });
    internal_static_google_storage_v1_ObjectChecksums_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_storage_v1_ObjectChecksums_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_ObjectChecksums_descriptor,
            new java.lang.String[] {
              "Crc32C", "Md5Hash",
            });
    internal_static_google_storage_v1_CommonEnums_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_storage_v1_CommonEnums_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_CommonEnums_descriptor, new java.lang.String[] {});
    internal_static_google_storage_v1_ContentRange_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_storage_v1_ContentRange_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_ContentRange_descriptor,
            new java.lang.String[] {
              "Start", "End", "CompleteLength",
            });
    internal_static_google_storage_v1_HmacKeyMetadata_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_storage_v1_HmacKeyMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_HmacKeyMetadata_descriptor,
            new java.lang.String[] {
              "Id",
              "AccessId",
              "ProjectId",
              "ServiceAccountEmail",
              "State",
              "TimeCreated",
              "Updated",
              "Etag",
            });
    internal_static_google_storage_v1_Notification_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_storage_v1_Notification_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Notification_descriptor,
            new java.lang.String[] {
              "Topic",
              "EventTypes",
              "CustomAttributes",
              "Etag",
              "ObjectNamePrefix",
              "PayloadFormat",
              "Id",
            });
    internal_static_google_storage_v1_Notification_CustomAttributesEntry_descriptor =
        internal_static_google_storage_v1_Notification_descriptor.getNestedTypes().get(0);
    internal_static_google_storage_v1_Notification_CustomAttributesEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Notification_CustomAttributesEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_storage_v1_ListNotificationsResponse_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_storage_v1_ListNotificationsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_ListNotificationsResponse_descriptor,
            new java.lang.String[] {
              "Items",
            });
    internal_static_google_storage_v1_Object_descriptor = getDescriptor().getMessageTypes().get(13);
    internal_static_google_storage_v1_Object_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Object_descriptor,
            new java.lang.String[] {
              "ContentEncoding",
              "ContentDisposition",
              "CacheControl",
              "Acl",
              "ContentLanguage",
              "Metageneration",
              "TimeDeleted",
              "ContentType",
              "Size",
              "TimeCreated",
              "Crc32C",
              "ComponentCount",
              "Md5Hash",
              "Etag",
              "Updated",
              "StorageClass",
              "KmsKeyName",
              "TimeStorageClassUpdated",
              "TemporaryHold",
              "RetentionExpirationTime",
              "Metadata",
              "EventBasedHold",
              "Name",
              "Id",
              "Bucket",
              "Generation",
              "Owner",
              "CustomerEncryption",
            });
    internal_static_google_storage_v1_Object_CustomerEncryption_descriptor =
        internal_static_google_storage_v1_Object_descriptor.getNestedTypes().get(0);
    internal_static_google_storage_v1_Object_CustomerEncryption_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Object_CustomerEncryption_descriptor,
            new java.lang.String[] {
              "EncryptionAlgorithm", "KeySha256",
            });
    internal_static_google_storage_v1_Object_MetadataEntry_descriptor =
        internal_static_google_storage_v1_Object_descriptor.getNestedTypes().get(1);
    internal_static_google_storage_v1_Object_MetadataEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Object_MetadataEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_storage_v1_ObjectAccessControl_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_storage_v1_ObjectAccessControl_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_ObjectAccessControl_descriptor,
            new java.lang.String[] {
              "Role",
              "Etag",
              "Id",
              "Bucket",
              "Object",
              "Generation",
              "Entity",
              "EntityId",
              "Email",
              "Domain",
              "ProjectTeam",
            });
    internal_static_google_storage_v1_ListObjectAccessControlsResponse_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_storage_v1_ListObjectAccessControlsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_ListObjectAccessControlsResponse_descriptor,
            new java.lang.String[] {
              "Items",
            });
    internal_static_google_storage_v1_ListObjectsResponse_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_storage_v1_ListObjectsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_ListObjectsResponse_descriptor,
            new java.lang.String[] {
              "Prefixes", "Items", "NextPageToken",
            });
    internal_static_google_storage_v1_ProjectTeam_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_storage_v1_ProjectTeam_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_ProjectTeam_descriptor,
            new java.lang.String[] {
              "ProjectNumber", "Team",
            });
    internal_static_google_storage_v1_ServiceAccount_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_google_storage_v1_ServiceAccount_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_ServiceAccount_descriptor,
            new java.lang.String[] {
              "EmailAddress",
            });
    internal_static_google_storage_v1_Owner_descriptor = getDescriptor().getMessageTypes().get(19);
    internal_static_google_storage_v1_Owner_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_storage_v1_Owner_descriptor,
            new java.lang.String[] {
              "Entity", "EntityId",
            });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
