/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/storage/v1/storage.proto

package com.google.storage.v1;

/**
 *
 *
 * <pre>
 * Request message for GetBucket.
 * </pre>
 *
 * Protobuf type {@code google.storage.v1.GetBucketRequest}
 */
public final class GetBucketRequest extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.storage.v1.GetBucketRequest)
    GetBucketRequestOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use GetBucketRequest.newBuilder() to construct.
  private GetBucketRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private GetBucketRequest() {
    bucket_ = "";
    projection_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new GetBucketRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private GetBucketRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10:
            {
              java.lang.String s = input.readStringRequireUtf8();

              bucket_ = s;
              break;
            }
          case 18:
            {
              com.google.protobuf.Int64Value.Builder subBuilder = null;
              if (ifMetagenerationMatch_ != null) {
                subBuilder = ifMetagenerationMatch_.toBuilder();
              }
              ifMetagenerationMatch_ =
                  input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ifMetagenerationMatch_);
                ifMetagenerationMatch_ = subBuilder.buildPartial();
              }

              break;
            }
          case 26:
            {
              com.google.protobuf.Int64Value.Builder subBuilder = null;
              if (ifMetagenerationNotMatch_ != null) {
                subBuilder = ifMetagenerationNotMatch_.toBuilder();
              }
              ifMetagenerationNotMatch_ =
                  input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ifMetagenerationNotMatch_);
                ifMetagenerationNotMatch_ = subBuilder.buildPartial();
              }

              break;
            }
          case 32:
            {
              int rawValue = input.readEnum();

              projection_ = rawValue;
              break;
            }
          case 50:
            {
              com.google.storage.v1.CommonRequestParams.Builder subBuilder = null;
              if (commonRequestParams_ != null) {
                subBuilder = commonRequestParams_.toBuilder();
              }
              commonRequestParams_ =
                  input.readMessage(
                      com.google.storage.v1.CommonRequestParams.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(commonRequestParams_);
                commonRequestParams_ = subBuilder.buildPartial();
              }

              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.storage.v1.StorageOuterClass
        .internal_static_google_storage_v1_GetBucketRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.storage.v1.StorageOuterClass
        .internal_static_google_storage_v1_GetBucketRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.storage.v1.GetBucketRequest.class,
            com.google.storage.v1.GetBucketRequest.Builder.class);
  }

  public static final int BUCKET_FIELD_NUMBER = 1;
  private volatile java.lang.Object bucket_;
  /**
   *
   *
   * <pre>
   * Required. Name of a bucket.
   * </pre>
   *
   * <code>string bucket = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The bucket.
   */
  public java.lang.String getBucket() {
    java.lang.Object ref = bucket_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bucket_ = s;
      return s;
    }
  }
  /**
   *
   *
   * <pre>
   * Required. Name of a bucket.
   * </pre>
   *
   * <code>string bucket = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The bytes for bucket.
   */
  public com.google.protobuf.ByteString getBucketBytes() {
    java.lang.Object ref = bucket_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
      bucket_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IF_METAGENERATION_MATCH_FIELD_NUMBER = 2;
  private com.google.protobuf.Int64Value ifMetagenerationMatch_;
  /**
   *
   *
   * <pre>
   * Makes the return of the bucket metadata conditional on whether the bucket's
   * current metageneration matches the given value.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value if_metageneration_match = 2;</code>
   *
   * @return Whether the ifMetagenerationMatch field is set.
   */
  public boolean hasIfMetagenerationMatch() {
    return ifMetagenerationMatch_ != null;
  }
  /**
   *
   *
   * <pre>
   * Makes the return of the bucket metadata conditional on whether the bucket's
   * current metageneration matches the given value.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value if_metageneration_match = 2;</code>
   *
   * @return The ifMetagenerationMatch.
   */
  public com.google.protobuf.Int64Value getIfMetagenerationMatch() {
    return ifMetagenerationMatch_ == null
        ? com.google.protobuf.Int64Value.getDefaultInstance()
        : ifMetagenerationMatch_;
  }
  /**
   *
   *
   * <pre>
   * Makes the return of the bucket metadata conditional on whether the bucket's
   * current metageneration matches the given value.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value if_metageneration_match = 2;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getIfMetagenerationMatchOrBuilder() {
    return getIfMetagenerationMatch();
  }

  public static final int IF_METAGENERATION_NOT_MATCH_FIELD_NUMBER = 3;
  private com.google.protobuf.Int64Value ifMetagenerationNotMatch_;
  /**
   *
   *
   * <pre>
   * Makes the return of the bucket metadata conditional on whether the bucket's
   * current metageneration does not match the given value.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value if_metageneration_not_match = 3;</code>
   *
   * @return Whether the ifMetagenerationNotMatch field is set.
   */
  public boolean hasIfMetagenerationNotMatch() {
    return ifMetagenerationNotMatch_ != null;
  }
  /**
   *
   *
   * <pre>
   * Makes the return of the bucket metadata conditional on whether the bucket's
   * current metageneration does not match the given value.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value if_metageneration_not_match = 3;</code>
   *
   * @return The ifMetagenerationNotMatch.
   */
  public com.google.protobuf.Int64Value getIfMetagenerationNotMatch() {
    return ifMetagenerationNotMatch_ == null
        ? com.google.protobuf.Int64Value.getDefaultInstance()
        : ifMetagenerationNotMatch_;
  }
  /**
   *
   *
   * <pre>
   * Makes the return of the bucket metadata conditional on whether the bucket's
   * current metageneration does not match the given value.
   * </pre>
   *
   * <code>.google.protobuf.Int64Value if_metageneration_not_match = 3;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getIfMetagenerationNotMatchOrBuilder() {
    return getIfMetagenerationNotMatch();
  }

  public static final int PROJECTION_FIELD_NUMBER = 4;
  private int projection_;
  /**
   *
   *
   * <pre>
   * Set of properties to return. Defaults to `NO_ACL`.
   * </pre>
   *
   * <code>.google.storage.v1.CommonEnums.Projection projection = 4;</code>
   *
   * @return The enum numeric value on the wire for projection.
   */
  public int getProjectionValue() {
    return projection_;
  }
  /**
   *
   *
   * <pre>
   * Set of properties to return. Defaults to `NO_ACL`.
   * </pre>
   *
   * <code>.google.storage.v1.CommonEnums.Projection projection = 4;</code>
   *
   * @return The projection.
   */
  public com.google.storage.v1.CommonEnums.Projection getProjection() {
    @SuppressWarnings("deprecation")
    com.google.storage.v1.CommonEnums.Projection result =
        com.google.storage.v1.CommonEnums.Projection.valueOf(projection_);
    return result == null ? com.google.storage.v1.CommonEnums.Projection.UNRECOGNIZED : result;
  }

  public static final int COMMON_REQUEST_PARAMS_FIELD_NUMBER = 6;
  private com.google.storage.v1.CommonRequestParams commonRequestParams_;
  /**
   *
   *
   * <pre>
   * A set of parameters common to all Storage API requests.
   * </pre>
   *
   * <code>.google.storage.v1.CommonRequestParams common_request_params = 6;</code>
   *
   * @return Whether the commonRequestParams field is set.
   */
  public boolean hasCommonRequestParams() {
    return commonRequestParams_ != null;
  }
  /**
   *
   *
   * <pre>
   * A set of parameters common to all Storage API requests.
   * </pre>
   *
   * <code>.google.storage.v1.CommonRequestParams common_request_params = 6;</code>
   *
   * @return The commonRequestParams.
   */
  public com.google.storage.v1.CommonRequestParams getCommonRequestParams() {
    return commonRequestParams_ == null
        ? com.google.storage.v1.CommonRequestParams.getDefaultInstance()
        : commonRequestParams_;
  }
  /**
   *
   *
   * <pre>
   * A set of parameters common to all Storage API requests.
   * </pre>
   *
   * <code>.google.storage.v1.CommonRequestParams common_request_params = 6;</code>
   */
  public com.google.storage.v1.CommonRequestParamsOrBuilder getCommonRequestParamsOrBuilder() {
    return getCommonRequestParams();
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (!getBucketBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, bucket_);
    }
    if (ifMetagenerationMatch_ != null) {
      output.writeMessage(2, getIfMetagenerationMatch());
    }
    if (ifMetagenerationNotMatch_ != null) {
      output.writeMessage(3, getIfMetagenerationNotMatch());
    }
    if (projection_
        != com.google.storage.v1.CommonEnums.Projection.PROJECTION_UNSPECIFIED.getNumber()) {
      output.writeEnum(4, projection_);
    }
    if (commonRequestParams_ != null) {
      output.writeMessage(6, getCommonRequestParams());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBucketBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, bucket_);
    }
    if (ifMetagenerationMatch_ != null) {
      size +=
          com.google.protobuf.CodedOutputStream.computeMessageSize(2, getIfMetagenerationMatch());
    }
    if (ifMetagenerationNotMatch_ != null) {
      size +=
          com.google.protobuf.CodedOutputStream.computeMessageSize(
              3, getIfMetagenerationNotMatch());
    }
    if (projection_
        != com.google.storage.v1.CommonEnums.Projection.PROJECTION_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream.computeEnumSize(4, projection_);
    }
    if (commonRequestParams_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(6, getCommonRequestParams());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.storage.v1.GetBucketRequest)) {
      return super.equals(obj);
    }
    com.google.storage.v1.GetBucketRequest other = (com.google.storage.v1.GetBucketRequest) obj;

    if (!getBucket().equals(other.getBucket())) return false;
    if (hasIfMetagenerationMatch() != other.hasIfMetagenerationMatch()) return false;
    if (hasIfMetagenerationMatch()) {
      if (!getIfMetagenerationMatch().equals(other.getIfMetagenerationMatch())) return false;
    }
    if (hasIfMetagenerationNotMatch() != other.hasIfMetagenerationNotMatch()) return false;
    if (hasIfMetagenerationNotMatch()) {
      if (!getIfMetagenerationNotMatch().equals(other.getIfMetagenerationNotMatch())) return false;
    }
    if (projection_ != other.projection_) return false;
    if (hasCommonRequestParams() != other.hasCommonRequestParams()) return false;
    if (hasCommonRequestParams()) {
      if (!getCommonRequestParams().equals(other.getCommonRequestParams())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BUCKET_FIELD_NUMBER;
    hash = (53 * hash) + getBucket().hashCode();
    if (hasIfMetagenerationMatch()) {
      hash = (37 * hash) + IF_METAGENERATION_MATCH_FIELD_NUMBER;
      hash = (53 * hash) + getIfMetagenerationMatch().hashCode();
    }
    if (hasIfMetagenerationNotMatch()) {
      hash = (37 * hash) + IF_METAGENERATION_NOT_MATCH_FIELD_NUMBER;
      hash = (53 * hash) + getIfMetagenerationNotMatch().hashCode();
    }
    hash = (37 * hash) + PROJECTION_FIELD_NUMBER;
    hash = (53 * hash) + projection_;
    if (hasCommonRequestParams()) {
      hash = (37 * hash) + COMMON_REQUEST_PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getCommonRequestParams().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.storage.v1.GetBucketRequest parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.storage.v1.GetBucketRequest parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.storage.v1.GetBucketRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.storage.v1.GetBucketRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.storage.v1.GetBucketRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.storage.v1.GetBucketRequest parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.storage.v1.GetBucketRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.storage.v1.GetBucketRequest parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.storage.v1.GetBucketRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.storage.v1.GetBucketRequest parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.storage.v1.GetBucketRequest parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.storage.v1.GetBucketRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.google.storage.v1.GetBucketRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * Request message for GetBucket.
   * </pre>
   *
   * Protobuf type {@code google.storage.v1.GetBucketRequest}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.storage.v1.GetBucketRequest)
      com.google.storage.v1.GetBucketRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.storage.v1.StorageOuterClass
          .internal_static_google_storage_v1_GetBucketRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.storage.v1.StorageOuterClass
          .internal_static_google_storage_v1_GetBucketRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.storage.v1.GetBucketRequest.class,
              com.google.storage.v1.GetBucketRequest.Builder.class);
    }

    // Construct using com.google.storage.v1.GetBucketRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bucket_ = "";

      if (ifMetagenerationMatchBuilder_ == null) {
        ifMetagenerationMatch_ = null;
      } else {
        ifMetagenerationMatch_ = null;
        ifMetagenerationMatchBuilder_ = null;
      }
      if (ifMetagenerationNotMatchBuilder_ == null) {
        ifMetagenerationNotMatch_ = null;
      } else {
        ifMetagenerationNotMatch_ = null;
        ifMetagenerationNotMatchBuilder_ = null;
      }
      projection_ = 0;

      if (commonRequestParamsBuilder_ == null) {
        commonRequestParams_ = null;
      } else {
        commonRequestParams_ = null;
        commonRequestParamsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.storage.v1.StorageOuterClass
          .internal_static_google_storage_v1_GetBucketRequest_descriptor;
    }

    @java.lang.Override
    public com.google.storage.v1.GetBucketRequest getDefaultInstanceForType() {
      return com.google.storage.v1.GetBucketRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.storage.v1.GetBucketRequest build() {
      com.google.storage.v1.GetBucketRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.storage.v1.GetBucketRequest buildPartial() {
      com.google.storage.v1.GetBucketRequest result =
          new com.google.storage.v1.GetBucketRequest(this);
      result.bucket_ = bucket_;
      if (ifMetagenerationMatchBuilder_ == null) {
        result.ifMetagenerationMatch_ = ifMetagenerationMatch_;
      } else {
        result.ifMetagenerationMatch_ = ifMetagenerationMatchBuilder_.build();
      }
      if (ifMetagenerationNotMatchBuilder_ == null) {
        result.ifMetagenerationNotMatch_ = ifMetagenerationNotMatch_;
      } else {
        result.ifMetagenerationNotMatch_ = ifMetagenerationNotMatchBuilder_.build();
      }
      result.projection_ = projection_;
      if (commonRequestParamsBuilder_ == null) {
        result.commonRequestParams_ = commonRequestParams_;
      } else {
        result.commonRequestParams_ = commonRequestParamsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.storage.v1.GetBucketRequest) {
        return mergeFrom((com.google.storage.v1.GetBucketRequest) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.storage.v1.GetBucketRequest other) {
      if (other == com.google.storage.v1.GetBucketRequest.getDefaultInstance()) return this;
      if (!other.getBucket().isEmpty()) {
        bucket_ = other.bucket_;
        onChanged();
      }
      if (other.hasIfMetagenerationMatch()) {
        mergeIfMetagenerationMatch(other.getIfMetagenerationMatch());
      }
      if (other.hasIfMetagenerationNotMatch()) {
        mergeIfMetagenerationNotMatch(other.getIfMetagenerationNotMatch());
      }
      if (other.projection_ != 0) {
        setProjectionValue(other.getProjectionValue());
      }
      if (other.hasCommonRequestParams()) {
        mergeCommonRequestParams(other.getCommonRequestParams());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.storage.v1.GetBucketRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.storage.v1.GetBucketRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object bucket_ = "";
    /**
     *
     *
     * <pre>
     * Required. Name of a bucket.
     * </pre>
     *
     * <code>string bucket = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     *
     * @return The bucket.
     */
    public java.lang.String getBucket() {
      java.lang.Object ref = bucket_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bucket_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Required. Name of a bucket.
     * </pre>
     *
     * <code>string bucket = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     *
     * @return The bytes for bucket.
     */
    public com.google.protobuf.ByteString getBucketBytes() {
      java.lang.Object ref = bucket_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        bucket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     *
     *
     * <pre>
     * Required. Name of a bucket.
     * </pre>
     *
     * <code>string bucket = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     *
     * @param value The bucket to set.
     * @return This builder for chaining.
     */
    public Builder setBucket(java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }

      bucket_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Required. Name of a bucket.
     * </pre>
     *
     * <code>string bucket = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearBucket() {

      bucket_ = getDefaultInstance().getBucket();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Required. Name of a bucket.
     * </pre>
     *
     * <code>string bucket = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     *
     * @param value The bytes for bucket to set.
     * @return This builder for chaining.
     */
    public Builder setBucketBytes(com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);

      bucket_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Int64Value ifMetagenerationMatch_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value,
            com.google.protobuf.Int64Value.Builder,
            com.google.protobuf.Int64ValueOrBuilder>
        ifMetagenerationMatchBuilder_;
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration matches the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_match = 2;</code>
     *
     * @return Whether the ifMetagenerationMatch field is set.
     */
    public boolean hasIfMetagenerationMatch() {
      return ifMetagenerationMatchBuilder_ != null || ifMetagenerationMatch_ != null;
    }
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration matches the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_match = 2;</code>
     *
     * @return The ifMetagenerationMatch.
     */
    public com.google.protobuf.Int64Value getIfMetagenerationMatch() {
      if (ifMetagenerationMatchBuilder_ == null) {
        return ifMetagenerationMatch_ == null
            ? com.google.protobuf.Int64Value.getDefaultInstance()
            : ifMetagenerationMatch_;
      } else {
        return ifMetagenerationMatchBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration matches the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_match = 2;</code>
     */
    public Builder setIfMetagenerationMatch(com.google.protobuf.Int64Value value) {
      if (ifMetagenerationMatchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ifMetagenerationMatch_ = value;
        onChanged();
      } else {
        ifMetagenerationMatchBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration matches the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_match = 2;</code>
     */
    public Builder setIfMetagenerationMatch(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (ifMetagenerationMatchBuilder_ == null) {
        ifMetagenerationMatch_ = builderForValue.build();
        onChanged();
      } else {
        ifMetagenerationMatchBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration matches the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_match = 2;</code>
     */
    public Builder mergeIfMetagenerationMatch(com.google.protobuf.Int64Value value) {
      if (ifMetagenerationMatchBuilder_ == null) {
        if (ifMetagenerationMatch_ != null) {
          ifMetagenerationMatch_ =
              com.google.protobuf.Int64Value.newBuilder(ifMetagenerationMatch_)
                  .mergeFrom(value)
                  .buildPartial();
        } else {
          ifMetagenerationMatch_ = value;
        }
        onChanged();
      } else {
        ifMetagenerationMatchBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration matches the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_match = 2;</code>
     */
    public Builder clearIfMetagenerationMatch() {
      if (ifMetagenerationMatchBuilder_ == null) {
        ifMetagenerationMatch_ = null;
        onChanged();
      } else {
        ifMetagenerationMatch_ = null;
        ifMetagenerationMatchBuilder_ = null;
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration matches the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_match = 2;</code>
     */
    public com.google.protobuf.Int64Value.Builder getIfMetagenerationMatchBuilder() {

      onChanged();
      return getIfMetagenerationMatchFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration matches the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_match = 2;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getIfMetagenerationMatchOrBuilder() {
      if (ifMetagenerationMatchBuilder_ != null) {
        return ifMetagenerationMatchBuilder_.getMessageOrBuilder();
      } else {
        return ifMetagenerationMatch_ == null
            ? com.google.protobuf.Int64Value.getDefaultInstance()
            : ifMetagenerationMatch_;
      }
    }
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration matches the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_match = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value,
            com.google.protobuf.Int64Value.Builder,
            com.google.protobuf.Int64ValueOrBuilder>
        getIfMetagenerationMatchFieldBuilder() {
      if (ifMetagenerationMatchBuilder_ == null) {
        ifMetagenerationMatchBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Int64Value,
                com.google.protobuf.Int64Value.Builder,
                com.google.protobuf.Int64ValueOrBuilder>(
                getIfMetagenerationMatch(), getParentForChildren(), isClean());
        ifMetagenerationMatch_ = null;
      }
      return ifMetagenerationMatchBuilder_;
    }

    private com.google.protobuf.Int64Value ifMetagenerationNotMatch_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value,
            com.google.protobuf.Int64Value.Builder,
            com.google.protobuf.Int64ValueOrBuilder>
        ifMetagenerationNotMatchBuilder_;
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration does not match the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_not_match = 3;</code>
     *
     * @return Whether the ifMetagenerationNotMatch field is set.
     */
    public boolean hasIfMetagenerationNotMatch() {
      return ifMetagenerationNotMatchBuilder_ != null || ifMetagenerationNotMatch_ != null;
    }
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration does not match the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_not_match = 3;</code>
     *
     * @return The ifMetagenerationNotMatch.
     */
    public com.google.protobuf.Int64Value getIfMetagenerationNotMatch() {
      if (ifMetagenerationNotMatchBuilder_ == null) {
        return ifMetagenerationNotMatch_ == null
            ? com.google.protobuf.Int64Value.getDefaultInstance()
            : ifMetagenerationNotMatch_;
      } else {
        return ifMetagenerationNotMatchBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration does not match the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_not_match = 3;</code>
     */
    public Builder setIfMetagenerationNotMatch(com.google.protobuf.Int64Value value) {
      if (ifMetagenerationNotMatchBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ifMetagenerationNotMatch_ = value;
        onChanged();
      } else {
        ifMetagenerationNotMatchBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration does not match the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_not_match = 3;</code>
     */
    public Builder setIfMetagenerationNotMatch(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (ifMetagenerationNotMatchBuilder_ == null) {
        ifMetagenerationNotMatch_ = builderForValue.build();
        onChanged();
      } else {
        ifMetagenerationNotMatchBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration does not match the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_not_match = 3;</code>
     */
    public Builder mergeIfMetagenerationNotMatch(com.google.protobuf.Int64Value value) {
      if (ifMetagenerationNotMatchBuilder_ == null) {
        if (ifMetagenerationNotMatch_ != null) {
          ifMetagenerationNotMatch_ =
              com.google.protobuf.Int64Value.newBuilder(ifMetagenerationNotMatch_)
                  .mergeFrom(value)
                  .buildPartial();
        } else {
          ifMetagenerationNotMatch_ = value;
        }
        onChanged();
      } else {
        ifMetagenerationNotMatchBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration does not match the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_not_match = 3;</code>
     */
    public Builder clearIfMetagenerationNotMatch() {
      if (ifMetagenerationNotMatchBuilder_ == null) {
        ifMetagenerationNotMatch_ = null;
        onChanged();
      } else {
        ifMetagenerationNotMatch_ = null;
        ifMetagenerationNotMatchBuilder_ = null;
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration does not match the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_not_match = 3;</code>
     */
    public com.google.protobuf.Int64Value.Builder getIfMetagenerationNotMatchBuilder() {

      onChanged();
      return getIfMetagenerationNotMatchFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration does not match the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_not_match = 3;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getIfMetagenerationNotMatchOrBuilder() {
      if (ifMetagenerationNotMatchBuilder_ != null) {
        return ifMetagenerationNotMatchBuilder_.getMessageOrBuilder();
      } else {
        return ifMetagenerationNotMatch_ == null
            ? com.google.protobuf.Int64Value.getDefaultInstance()
            : ifMetagenerationNotMatch_;
      }
    }
    /**
     *
     *
     * <pre>
     * Makes the return of the bucket metadata conditional on whether the bucket's
     * current metageneration does not match the given value.
     * </pre>
     *
     * <code>.google.protobuf.Int64Value if_metageneration_not_match = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value,
            com.google.protobuf.Int64Value.Builder,
            com.google.protobuf.Int64ValueOrBuilder>
        getIfMetagenerationNotMatchFieldBuilder() {
      if (ifMetagenerationNotMatchBuilder_ == null) {
        ifMetagenerationNotMatchBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.protobuf.Int64Value,
                com.google.protobuf.Int64Value.Builder,
                com.google.protobuf.Int64ValueOrBuilder>(
                getIfMetagenerationNotMatch(), getParentForChildren(), isClean());
        ifMetagenerationNotMatch_ = null;
      }
      return ifMetagenerationNotMatchBuilder_;
    }

    private int projection_ = 0;
    /**
     *
     *
     * <pre>
     * Set of properties to return. Defaults to `NO_ACL`.
     * </pre>
     *
     * <code>.google.storage.v1.CommonEnums.Projection projection = 4;</code>
     *
     * @return The enum numeric value on the wire for projection.
     */
    public int getProjectionValue() {
      return projection_;
    }
    /**
     *
     *
     * <pre>
     * Set of properties to return. Defaults to `NO_ACL`.
     * </pre>
     *
     * <code>.google.storage.v1.CommonEnums.Projection projection = 4;</code>
     *
     * @param value The enum numeric value on the wire for projection to set.
     * @return This builder for chaining.
     */
    public Builder setProjectionValue(int value) {
      projection_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Set of properties to return. Defaults to `NO_ACL`.
     * </pre>
     *
     * <code>.google.storage.v1.CommonEnums.Projection projection = 4;</code>
     *
     * @return The projection.
     */
    public com.google.storage.v1.CommonEnums.Projection getProjection() {
      @SuppressWarnings("deprecation")
      com.google.storage.v1.CommonEnums.Projection result =
          com.google.storage.v1.CommonEnums.Projection.valueOf(projection_);
      return result == null ? com.google.storage.v1.CommonEnums.Projection.UNRECOGNIZED : result;
    }
    /**
     *
     *
     * <pre>
     * Set of properties to return. Defaults to `NO_ACL`.
     * </pre>
     *
     * <code>.google.storage.v1.CommonEnums.Projection projection = 4;</code>
     *
     * @param value The projection to set.
     * @return This builder for chaining.
     */
    public Builder setProjection(com.google.storage.v1.CommonEnums.Projection value) {
      if (value == null) {
        throw new NullPointerException();
      }

      projection_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * Set of properties to return. Defaults to `NO_ACL`.
     * </pre>
     *
     * <code>.google.storage.v1.CommonEnums.Projection projection = 4;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearProjection() {

      projection_ = 0;
      onChanged();
      return this;
    }

    private com.google.storage.v1.CommonRequestParams commonRequestParams_;
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.storage.v1.CommonRequestParams,
            com.google.storage.v1.CommonRequestParams.Builder,
            com.google.storage.v1.CommonRequestParamsOrBuilder>
        commonRequestParamsBuilder_;
    /**
     *
     *
     * <pre>
     * A set of parameters common to all Storage API requests.
     * </pre>
     *
     * <code>.google.storage.v1.CommonRequestParams common_request_params = 6;</code>
     *
     * @return Whether the commonRequestParams field is set.
     */
    public boolean hasCommonRequestParams() {
      return commonRequestParamsBuilder_ != null || commonRequestParams_ != null;
    }
    /**
     *
     *
     * <pre>
     * A set of parameters common to all Storage API requests.
     * </pre>
     *
     * <code>.google.storage.v1.CommonRequestParams common_request_params = 6;</code>
     *
     * @return The commonRequestParams.
     */
    public com.google.storage.v1.CommonRequestParams getCommonRequestParams() {
      if (commonRequestParamsBuilder_ == null) {
        return commonRequestParams_ == null
            ? com.google.storage.v1.CommonRequestParams.getDefaultInstance()
            : commonRequestParams_;
      } else {
        return commonRequestParamsBuilder_.getMessage();
      }
    }
    /**
     *
     *
     * <pre>
     * A set of parameters common to all Storage API requests.
     * </pre>
     *
     * <code>.google.storage.v1.CommonRequestParams common_request_params = 6;</code>
     */
    public Builder setCommonRequestParams(com.google.storage.v1.CommonRequestParams value) {
      if (commonRequestParamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        commonRequestParams_ = value;
        onChanged();
      } else {
        commonRequestParamsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * A set of parameters common to all Storage API requests.
     * </pre>
     *
     * <code>.google.storage.v1.CommonRequestParams common_request_params = 6;</code>
     */
    public Builder setCommonRequestParams(
        com.google.storage.v1.CommonRequestParams.Builder builderForValue) {
      if (commonRequestParamsBuilder_ == null) {
        commonRequestParams_ = builderForValue.build();
        onChanged();
      } else {
        commonRequestParamsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * A set of parameters common to all Storage API requests.
     * </pre>
     *
     * <code>.google.storage.v1.CommonRequestParams common_request_params = 6;</code>
     */
    public Builder mergeCommonRequestParams(com.google.storage.v1.CommonRequestParams value) {
      if (commonRequestParamsBuilder_ == null) {
        if (commonRequestParams_ != null) {
          commonRequestParams_ =
              com.google.storage.v1.CommonRequestParams.newBuilder(commonRequestParams_)
                  .mergeFrom(value)
                  .buildPartial();
        } else {
          commonRequestParams_ = value;
        }
        onChanged();
      } else {
        commonRequestParamsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * A set of parameters common to all Storage API requests.
     * </pre>
     *
     * <code>.google.storage.v1.CommonRequestParams common_request_params = 6;</code>
     */
    public Builder clearCommonRequestParams() {
      if (commonRequestParamsBuilder_ == null) {
        commonRequestParams_ = null;
        onChanged();
      } else {
        commonRequestParams_ = null;
        commonRequestParamsBuilder_ = null;
      }

      return this;
    }
    /**
     *
     *
     * <pre>
     * A set of parameters common to all Storage API requests.
     * </pre>
     *
     * <code>.google.storage.v1.CommonRequestParams common_request_params = 6;</code>
     */
    public com.google.storage.v1.CommonRequestParams.Builder getCommonRequestParamsBuilder() {

      onChanged();
      return getCommonRequestParamsFieldBuilder().getBuilder();
    }
    /**
     *
     *
     * <pre>
     * A set of parameters common to all Storage API requests.
     * </pre>
     *
     * <code>.google.storage.v1.CommonRequestParams common_request_params = 6;</code>
     */
    public com.google.storage.v1.CommonRequestParamsOrBuilder getCommonRequestParamsOrBuilder() {
      if (commonRequestParamsBuilder_ != null) {
        return commonRequestParamsBuilder_.getMessageOrBuilder();
      } else {
        return commonRequestParams_ == null
            ? com.google.storage.v1.CommonRequestParams.getDefaultInstance()
            : commonRequestParams_;
      }
    }
    /**
     *
     *
     * <pre>
     * A set of parameters common to all Storage API requests.
     * </pre>
     *
     * <code>.google.storage.v1.CommonRequestParams common_request_params = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            com.google.storage.v1.CommonRequestParams,
            com.google.storage.v1.CommonRequestParams.Builder,
            com.google.storage.v1.CommonRequestParamsOrBuilder>
        getCommonRequestParamsFieldBuilder() {
      if (commonRequestParamsBuilder_ == null) {
        commonRequestParamsBuilder_ =
            new com.google.protobuf.SingleFieldBuilderV3<
                com.google.storage.v1.CommonRequestParams,
                com.google.storage.v1.CommonRequestParams.Builder,
                com.google.storage.v1.CommonRequestParamsOrBuilder>(
                getCommonRequestParams(), getParentForChildren(), isClean());
        commonRequestParams_ = null;
      }
      return commonRequestParamsBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.storage.v1.GetBucketRequest)
  }

  // @@protoc_insertion_point(class_scope:google.storage.v1.GetBucketRequest)
  private static final com.google.storage.v1.GetBucketRequest DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.storage.v1.GetBucketRequest();
  }

  public static com.google.storage.v1.GetBucketRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetBucketRequest> PARSER =
      new com.google.protobuf.AbstractParser<GetBucketRequest>() {
        @java.lang.Override
        public GetBucketRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetBucketRequest(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<GetBucketRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetBucketRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.storage.v1.GetBucketRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
