/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/storage/v1/storage.proto

package com.google.storage.v1;

/**
 *
 *
 * <pre>
 * Response object for `ByteStream.QueryWriteStatus`.
 * </pre>
 *
 * Protobuf type {@code google.storage.v1.QueryWriteStatusResponse}
 */
public final class QueryWriteStatusResponse extends com.google.protobuf.GeneratedMessageV3
    implements
    // @@protoc_insertion_point(message_implements:google.storage.v1.QueryWriteStatusResponse)
    QueryWriteStatusResponseOrBuilder {
  private static final long serialVersionUID = 0L;
  // Use QueryWriteStatusResponse.newBuilder() to construct.
  private QueryWriteStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private QueryWriteStatusResponse() {}

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
    return new QueryWriteStatusResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
    return this.unknownFields;
  }

  private QueryWriteStatusResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8:
            {
              committedSize_ = input.readInt64();
              break;
            }
          case 16:
            {
              complete_ = input.readBool();
              break;
            }
          default:
            {
              if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return com.google.storage.v1.StorageOuterClass
        .internal_static_google_storage_v1_QueryWriteStatusResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.storage.v1.StorageOuterClass
        .internal_static_google_storage_v1_QueryWriteStatusResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.storage.v1.QueryWriteStatusResponse.class,
            com.google.storage.v1.QueryWriteStatusResponse.Builder.class);
  }

  public static final int COMMITTED_SIZE_FIELD_NUMBER = 1;
  private long committedSize_;
  /**
   *
   *
   * <pre>
   * The number of bytes that have been processed for the given object.
   * </pre>
   *
   * <code>int64 committed_size = 1;</code>
   *
   * @return The committedSize.
   */
  public long getCommittedSize() {
    return committedSize_;
  }

  public static final int COMPLETE_FIELD_NUMBER = 2;
  private boolean complete_;
  /**
   *
   *
   * <pre>
   * `complete` is `true` only if the client has sent a `InsertObjectRequest`
   * with `finish_write` set to true, and the server has processed that request.
   * </pre>
   *
   * <code>bool complete = 2;</code>
   *
   * @return The complete.
   */
  public boolean getComplete() {
    return complete_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (committedSize_ != 0L) {
      output.writeInt64(1, committedSize_);
    }
    if (complete_ != false) {
      output.writeBool(2, complete_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (committedSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream.computeInt64Size(1, committedSize_);
    }
    if (complete_ != false) {
      size += com.google.protobuf.CodedOutputStream.computeBoolSize(2, complete_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof com.google.storage.v1.QueryWriteStatusResponse)) {
      return super.equals(obj);
    }
    com.google.storage.v1.QueryWriteStatusResponse other =
        (com.google.storage.v1.QueryWriteStatusResponse) obj;

    if (getCommittedSize() != other.getCommittedSize()) return false;
    if (getComplete() != other.getComplete()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMITTED_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(getCommittedSize());
    hash = (37 * hash) + COMPLETE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getComplete());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.storage.v1.QueryWriteStatusResponse parseFrom(java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.storage.v1.QueryWriteStatusResponse parseFrom(
      java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.storage.v1.QueryWriteStatusResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.storage.v1.QueryWriteStatusResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.storage.v1.QueryWriteStatusResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static com.google.storage.v1.QueryWriteStatusResponse parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static com.google.storage.v1.QueryWriteStatusResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.storage.v1.QueryWriteStatusResponse parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.storage.v1.QueryWriteStatusResponse parseDelimitedFrom(
      java.io.InputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
  }

  public static com.google.storage.v1.QueryWriteStatusResponse parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
        PARSER, input, extensionRegistry);
  }

  public static com.google.storage.v1.QueryWriteStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input) throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
  }

  public static com.google.storage.v1.QueryWriteStatusResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
        PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(com.google.storage.v1.QueryWriteStatusResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   *
   *
   * <pre>
   * Response object for `ByteStream.QueryWriteStatus`.
   * </pre>
   *
   * Protobuf type {@code google.storage.v1.QueryWriteStatusResponse}
   */
  public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
      implements
      // @@protoc_insertion_point(builder_implements:google.storage.v1.QueryWriteStatusResponse)
      com.google.storage.v1.QueryWriteStatusResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return com.google.storage.v1.StorageOuterClass
          .internal_static_google_storage_v1_QueryWriteStatusResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.storage.v1.StorageOuterClass
          .internal_static_google_storage_v1_QueryWriteStatusResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.storage.v1.QueryWriteStatusResponse.class,
              com.google.storage.v1.QueryWriteStatusResponse.Builder.class);
    }

    // Construct using com.google.storage.v1.QueryWriteStatusResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      committedSize_ = 0L;

      complete_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.storage.v1.StorageOuterClass
          .internal_static_google_storage_v1_QueryWriteStatusResponse_descriptor;
    }

    @java.lang.Override
    public com.google.storage.v1.QueryWriteStatusResponse getDefaultInstanceForType() {
      return com.google.storage.v1.QueryWriteStatusResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.storage.v1.QueryWriteStatusResponse build() {
      com.google.storage.v1.QueryWriteStatusResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.storage.v1.QueryWriteStatusResponse buildPartial() {
      com.google.storage.v1.QueryWriteStatusResponse result =
          new com.google.storage.v1.QueryWriteStatusResponse(this);
      result.committedSize_ = committedSize_;
      result.complete_ = complete_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.storage.v1.QueryWriteStatusResponse) {
        return mergeFrom((com.google.storage.v1.QueryWriteStatusResponse) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.storage.v1.QueryWriteStatusResponse other) {
      if (other == com.google.storage.v1.QueryWriteStatusResponse.getDefaultInstance()) return this;
      if (other.getCommittedSize() != 0L) {
        setCommittedSize(other.getCommittedSize());
      }
      if (other.getComplete() != false) {
        setComplete(other.getComplete());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.storage.v1.QueryWriteStatusResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.storage.v1.QueryWriteStatusResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long committedSize_;
    /**
     *
     *
     * <pre>
     * The number of bytes that have been processed for the given object.
     * </pre>
     *
     * <code>int64 committed_size = 1;</code>
     *
     * @return The committedSize.
     */
    public long getCommittedSize() {
      return committedSize_;
    }
    /**
     *
     *
     * <pre>
     * The number of bytes that have been processed for the given object.
     * </pre>
     *
     * <code>int64 committed_size = 1;</code>
     *
     * @param value The committedSize to set.
     * @return This builder for chaining.
     */
    public Builder setCommittedSize(long value) {

      committedSize_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * The number of bytes that have been processed for the given object.
     * </pre>
     *
     * <code>int64 committed_size = 1;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearCommittedSize() {

      committedSize_ = 0L;
      onChanged();
      return this;
    }

    private boolean complete_;
    /**
     *
     *
     * <pre>
     * `complete` is `true` only if the client has sent a `InsertObjectRequest`
     * with `finish_write` set to true, and the server has processed that request.
     * </pre>
     *
     * <code>bool complete = 2;</code>
     *
     * @return The complete.
     */
    public boolean getComplete() {
      return complete_;
    }
    /**
     *
     *
     * <pre>
     * `complete` is `true` only if the client has sent a `InsertObjectRequest`
     * with `finish_write` set to true, and the server has processed that request.
     * </pre>
     *
     * <code>bool complete = 2;</code>
     *
     * @param value The complete to set.
     * @return This builder for chaining.
     */
    public Builder setComplete(boolean value) {

      complete_ = value;
      onChanged();
      return this;
    }
    /**
     *
     *
     * <pre>
     * `complete` is `true` only if the client has sent a `InsertObjectRequest`
     * with `finish_write` set to true, and the server has processed that request.
     * </pre>
     *
     * <code>bool complete = 2;</code>
     *
     * @return This builder for chaining.
     */
    public Builder clearComplete() {

      complete_ = false;
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:google.storage.v1.QueryWriteStatusResponse)
  }

  // @@protoc_insertion_point(class_scope:google.storage.v1.QueryWriteStatusResponse)
  private static final com.google.storage.v1.QueryWriteStatusResponse DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new com.google.storage.v1.QueryWriteStatusResponse();
  }

  public static com.google.storage.v1.QueryWriteStatusResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryWriteStatusResponse> PARSER =
      new com.google.protobuf.AbstractParser<QueryWriteStatusResponse>() {
        @java.lang.Override
        public QueryWriteStatusResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new QueryWriteStatusResponse(input, extensionRegistry);
        }
      };

  public static com.google.protobuf.Parser<QueryWriteStatusResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryWriteStatusResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.storage.v1.QueryWriteStatusResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }
}
