// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/storage/v2/storage.proto

package com.google.storage.v2;

public interface CommonRequestParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.storage.v2.CommonRequestParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. Required when using buckets with Requestor Pays feature enabled.
   * </pre>
   *
   * <code>string user_project = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The userProject.
   */
  java.lang.String getUserProject();
  /**
   * <pre>
   * Required. Required when using buckets with Requestor Pays feature enabled.
   * </pre>
   *
   * <code>string user_project = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }</code>
   * @return The bytes for userProject.
   */
  com.google.protobuf.ByteString
      getUserProjectBytes();
}
