steps:
- name: gcr.io/cloud-devrel-public-resources/java8
  entrypoint: ls
  args: [
    '-alt',
  ]
- name: gcr.io/cloud-devrel-public-resources/java8
  entrypoint: curl
  args: [
    '--header',
    'Metadata-Flavor: Google',
    'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/email'
  ]
- name: gcr.io/cloud-devrel-public-resources/java8
  entrypoint: pwd
- name: gcr.io/cloud-devrel-public-resources/java8
  entrypoint: bash
  args: [
    '.kokoro/build.sh'
  ]
  env:
  - 'JOB_TYPE=samples'
  - 'GOOGLE_CLOUD_PROJECT=cloud-java-ci-sample'
  - 'GOOGLE_CLOUD_PROJECT_NUMBER=615621127317'
  - 'IT_SERVICE_ACCOUNT_EMAIL=samples@cloud-java-ci-sample.iam.gserviceaccount.com'
- name: gcr.io/cloud-devrel-public-resources/java8
  entrypoint: echo
  args: [
    'Sample job succeeded',
  ]
timeout: 3600s
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET


